P8105 HW2
================
2022-10-04

``` r
library(readxl)
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.1      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(tidyr)
```

# Problem 2

\#cleaning Mr. Trash Wheel sheet

``` r
wheel_data = read_excel("data/Trash Wheel Collection Data.xlsx",
                        range = "A2:N550",
                        sheet = "Mr. Trash Wheel") %>% janitor::clean_names()

wheel_data = wheel_data %>% mutate(sports_balls = as.integer(sports_balls))%>%drop_na(dumpster)%>% mutate(vessel_type="Mr. Trash Wheel")%>%mutate(year=as.double(year))
```

\#cleaning Prof Trash Wheel sheet

``` r
prof_data = read_excel("data/Trash Wheel Collection Data.xlsx",
                        na = "",
                        sheet = "Professor Trash Wheel") %>% janitor::clean_names()%>% drop_na(dumpster)%>%mutate(vessel_type = "Professor Trash Wheel")
```

\#combine two data set

``` r
tidy_data = bind_rows(wheel_data, prof_data)
tidy_data%>% 
  filter(vessel_type == "Professor Trash Wheel")%>%
  select(weight_tons)%>%
  sum()
```

    ## [1] 190.12

``` r
tidy_data%>%
  filter(year==2020,vessel_type == "Mr. Trash Wheel")%>%
  select(sports_balls)%>%
  sum()
```

    ## [1] 856

After combining these two datasets, the new dataset contains 641 rows
and 15 columns, key variables including: dumpster, month, year, date,
weight_tons, volume_cubic_yards, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, grocery_bags, chip_bags, sports_balls,
homes_powered and the new adding variable vessel_type which helps
indicate the data source. For the data we got, we can obtained that the
total weight of trash collected by Professor Trash Wheel is 190.12 tons,
and the total number of sports balls collected by Mr. Trash Wheel in
2020 is 856.

# Problem 3

\#cleaning data in plos-month

``` r
pols_month = read_csv(file = "data/fivethirtyeight_datasets/pols-month.csv")%>% janitor::clean_names()
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
tidy_pols = pols_month%>%
  separate(mon,into = c("year", "month", "day"), sep = "-")%>%
  mutate(president = ifelse(prez_dem==0, "gop", "dem"))%>%
  mutate(month = month.name[as.numeric(month)], year = as.integer(year))%>%
  select(-prez_dem, -prez_gop, -day)
  
tidy_pols
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

\#cleaning data in snp.csv

``` r
snp = read_csv(file = "data/fivethirtyeight_datasets/snp.csv")%>% janitor::clean_names()
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
tidy_snp = snp%>%
  separate(date,into = c("month", "day","year"), sep = "/")%>%
  mutate(month = month.name[as.integer(month)], year = as.integer(year), day = as.integer(day))%>%
  mutate(year = as.integer(ifelse(year>=15, year+1900, year+2000)))%>%
  select(year, month, close)%>%arrange(year, month)

tidy_snp
```

    ## # A tibble: 787 × 3
    ##     year month     close
    ##    <int> <chr>     <dbl>
    ##  1  1915 April    2086. 
    ##  2  1915 February 2104. 
    ##  3  1915 January  1995. 
    ##  4  1915 July     2080. 
    ##  5  1915 June     2063. 
    ##  6  1915 March    2068. 
    ##  7  1915 May      2107. 
    ##  8  1950 April      18.0
    ##  9  1950 August     18.4
    ## 10  1950 December   20.4
    ## # … with 777 more rows

\#cleaning the unemployment data

``` r
emp = read_csv(file = "data/fivethirtyeight_datasets/unemployment.csv")%>% janitor::clean_names()
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
tidy_emp = emp%>%
  pivot_longer(2:13, names_to = "month", values_to = "unemploy")%>%
  mutate(month = recode(month, 
                        'jan'='January',
                        'feb'='February',
                        'mar'='March',
                        'apr'='April',
                        'may'='May',
                        'jun'='June',
                        'jul'='July',
                        'aug'='August',
                        'sep'='September',
                        'oct'='October',
                        'nov'='November',
                        'dec'='December'), year = as.integer(year))

tidy_emp
```

    ## # A tibble: 816 × 3
    ##     year month     unemploy
    ##    <int> <chr>        <dbl>
    ##  1  1948 January        3.4
    ##  2  1948 February       3.8
    ##  3  1948 March          4  
    ##  4  1948 April          3.9
    ##  5  1948 May            3.5
    ##  6  1948 June           3.6
    ##  7  1948 July           3.6
    ##  8  1948 August         3.9
    ##  9  1948 September      3.8
    ## 10  1948 October        3.7
    ## # … with 806 more rows

\#combine the three datasets

``` r
tidy_combine = full_join(tidy_pols, tidy_snp)%>% full_join(tidy_emp)
```

    ## Joining, by = c("year", "month")
    ## Joining, by = c("year", "month")

``` r
tidy_combine
```

    ## # A tibble: 835 × 11
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ close
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <dbl>
    ##  1  1947 January        23      51     253      23      45     198 dem        NA
    ##  2  1947 February       23      51     253      23      45     198 dem        NA
    ##  3  1947 March          23      51     253      23      45     198 dem        NA
    ##  4  1947 April          23      51     253      23      45     198 dem        NA
    ##  5  1947 May            23      51     253      23      45     198 dem        NA
    ##  6  1947 June           23      51     253      23      45     198 dem        NA
    ##  7  1947 July           23      51     253      23      45     198 dem        NA
    ##  8  1947 August         23      51     253      23      45     198 dem        NA
    ##  9  1947 September      23      51     253      23      45     198 dem        NA
    ## 10  1947 October        23      51     253      23      45     198 dem        NA
    ## # … with 825 more rows, 1 more variable: unemploy <dbl>, and abbreviated
    ## #   variable name ¹​president

After combing the three data sets, the new dataset obtained contains 645
rows and 12 columns, which gives the dimension of 828 x 11, and the
range of years is 68, the key variables are listed as follow: year month
gov_gop: \# of republican governors with associated time. sen_gop: \# of
republican senators with associated time. rep_gop: \# of republican
representatives with associated time. gov_dem: \# of democratic
governors with associated time. sen_dem: \# of democratic senators with
associated time. rep_dem: \# of democratic representatives with
associated time. president: indicate the party of president with
associated time. close: the closing value of stock index. unemploy_perc:
the unemployment percentage with associated time.
